# Generated by Django 5.2.6 on 2025-09-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_category_slug_alter_article_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='decription',
            new_name='description',
        ),
    ]
